### ISSUE TITLE
Channel stats, info, actions

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash-cloud-announcer#23]
could we have stats/actions at the top of cloud user channels like axolo does for their PR channels ?
How many tickets are being tracked by cloudy in that channel, their instance url, etc

Screenshot from axolo channel 
![Screenshot 2022-11-02 at 16 14 00](https://user-images.githubusercontent.com/9117144/199545188-0f67ad01-c088-4dbc-a0dd-0aebb0b7e6dc.png)

**Comment by owlas** [comment]
Added the total number of open requests to the channel bookmarks. We should open a separate issue for tracking instance url (and maybe version of instance?)
